[build]
  functions = "netlify/functions"
  publish = "."

[dev]
  framework = "#static"
  port = 3000
  publish = "."
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200 